=== HulFlyS/LM_1617_Juan_Gil/lm/practica2_xml_dtd/Ex5.dtd
<!ELEMENT matches (match)*>	
<!ELEMENT match (hometeam,visitorteam,scores,yellowcard,redcard)>	
<!ELEMENT hometeam (#PCDATA)>	
<!ELEMENT visitorteam (#PCDATA)>	
<!ELEMENT scores (score)*>	
<!ELEMENT yellowcard (player)*>	
<!ELEMENT redcard (player)*>	
<!ELEMENT score (player)*>	
<!ELEMENT player (#PCDATA)>	
<!ATTLIST match score CDATA #REQUIRED>	
<!ATTLIST score time CDATA #REQUIRED>	
<!ATTLIST score gol CDATA #REQUIRED>

=== HulFlyS/LM_1617_Juan_Gil/lm/practica2_xml_dtd/Ex5.xml
<?xml version="1.0"?>
<!DOCTYPE games SYSTEM "Ex5.dtd">
<matches>	
    <match	score="2-1">	
	 	<hometeam>Betis</hometeam>	
	 	<visitorteam>Sevilla</visitorteam>	
	 	<scores>	
            <score time= "23">	
                <player>Ruben Castro</player>	
            </score>	
            <score	time="53" gol="penalty">	
                <player>Vietto</player>	
            </score>	
             <score	time="81">	
                <player>Alex Alegr√≠a</player>	
            </score>
        </scores>	
        <yellowcard>
            <player>Vietto</player>	
            <player>Durmisi</player>
            <player>Piccini</player>
        </yellowcard>	
        <redcard>	
	 	     <player>Nasri</player>	
        </redcard>	
    </match>	
</matches>
